version: '3.8'

services:
  elercam:
    image: ghcr.io/mksavin/elercam:latest
    # build: .
    container_name: elercam
    restart: unless-stopped
    environment:
      DATABASE_URL: mongodb://mongo:27017/elercam?authSource=admin
    volumes:
      - ./.env:/app/.env
      - ./config.ts:/app/config.ts
    networks:
      - mosquitto
    env_file: .env

  mongo:
    build:
      context: .deployment/mongo
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: host.docker.internal
      MONGO_REPLICA_PORT: 27017
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: 'mongosh'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '27017:27017'
    restart: unless-stopped
    healthcheck:
      # Use "mongo" instead of "mongosh" before v5.0
      test: [ 'CMD', 'mongosh', 'admin', '--port', '27017', '--eval', "db.adminCommand('ping').ok" ]
      interval: 5s
      timeout: 2s
      retries: 20

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #  ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

networks:
  mosquitto:
    external: true
