services:
  spotter-bot:
    image: ghcr.io/mksavin/spotter-bot:latest
    # build: .
    container_name: spotter-bot
    restart: unless-stopped
    volumes:
      - ./.env.bot:/app/.env
      - ./bot.config.ts:/app/config.ts
      # Persist the SQLite database across container restarts.
      - ./.docker/bot:/app/data
    networks:
      - kafka
      - minio
    depends_on:
      - kafka
      - minio

  spotter-depot-1:
    image: ghcr.io/mksavin/spotter-depot:latest
    restart: unless-stopped
    networks:
      - kafka
      - minio
    depends_on:
      - kafka
      - minio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [ gpu ]
    devices:
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    volumes:
      - .env.depot-1:/app/.env

  spotter-depot-2:
    image: ghcr.io/mksavin/spotter-depot:latest
    restart: unless-stopped
    networks:
      - kafka
      - minio
    depends_on:
      - kafka
      - minio
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ['0'] # this is only needed when using multiple GPUs
              count: 1 # number of GPUs
              capabilities: [ gpu ]
    devices:
      - /dev/nvidia-caps:/dev/nvidia-caps
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    volumes:
      - .env.depot-2:/app/.env

  spotter-sink:
    image: ghcr.io/mksavin/spotter-sink:latest
    restart: unless-stopped
    volumes:
      - .env.sink:/app/.env
    networks:
      - mosquitto
      - kafka
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    restart: unless-stopped
    networks:
      - kafka
    # KRaft mode (no Zookeeper) configuration for a single-node cluster
    ports:
      - '9092:9092'
      - '9997:9997'
      - '29092:29092'
    environment:
      CLUSTER_ID: "q8RkVBbMQYel-fULGNEbNQ"
      KAFKA_KRAFT_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_LOG4J_LOGGERS: "org.apache.kafka.image.loader.MetadataLoader=WARN"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - kafka
    depends_on:
      - zookeeper
      - kafka
    ports:
      - '8082:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997

  kafka-init:
    image: confluentinc/cp-kafka:latest
    networks:
      - kafka
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.event --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.event.test_seed --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.event.media_requested --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.event.media_processed --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.camera.frame_requested --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.camera.frame_processed --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

  #  minio:
  #    volumes:
  #      - .docker/minio:/data
  #    image: quay.io/minio/minio:latest
  #    command: server --console-address ":9001" /data/minio
  #    ports:
  #      - '9010:9000'
  #      - '9011:9001'
  #    networks:
  #      - minio
  #    environment:
  #      MINIO_ROOT_USER: admin
  #      MINIO_ROOT_PASSWORD: some-minio-access
  #      MINIO_BROWSER_REDIRECT_URL: "${MINIO_BROWSER_URL}"
  #    healthcheck:
  #      test: ['CMD', 'mc', 'ready', 'local']
  #      interval: 5s
  #      timeout: 5s
  #      retries: 5

networks:
  minio:
    driver: bridge
  kafka:
    driver: bridge
  mosquitto:
    external: true
