services:
  mongo:
    build:
      context: .deployment/mongo
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: host.docker.internal
      MONGO_REPLICA_PORT: 27017
      # Use "mongo" instead of "mongosh" before v5.0
      MONGO_COMMAND: 'mongosh'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '27017:27017'
    restart: unless-stopped
    healthcheck:
      # Use "mongo" instead of "mongosh" before v5.0
      test: [ 'CMD', 'mongosh', 'admin', '--port', '27017', '--eval', "db.adminCommand('ping').ok" ]
      interval: 5s
      timeout: 2s
      retries: 20

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - '8081:8081'
    depends_on:
      - mongo
    environment:
      #  ME_CONFIG_MONGODB_ADMINUSERNAME: root
      #  ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    restart: unless-stopped
    networks:
      - kafka
    ports:
      - '9092:9092'
      - '9997:9997'
      - '29092:29092'
    environment:
      CLUSTER_ID: "q8RkVBbMQYel-fULGNEbNQ"
      KAFKA_KRAFT_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_LOG4J_LOGGERS: "org.apache.kafka.image.loader.MetadataLoader=WARN"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:9092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    networks:
      - kafka
    ports:
      - '8082:8080'
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997

  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    networks:
      - kafka
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.event --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.event.test_seed --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.event.media_requested --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.event.media_processed --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.camera.frame_requested --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic spotter.camera.frame_processed --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

  #  garage:
  #    image: dxflrs/garage:v1.1.0
  #    restart: unless-stopped
  #    environment:
  #      - GARAGE_RPC_SECRET=b60a083b0e334f939312a67d508ed425770c6497c6ae86371b369bf7365f5c95
  #      - GARAGE_ADMIN_TOKEN=test_admin_token
  #      - GARAGE_METRICS_TOKEN=test_admin_token
  #    ports:
  #      - '3900:3900'
  #      - '3901:3901'
  #      - '3902:3902'
  #      - '3903:3903'
  #    volumes:
  #      - .deployment/garage/garage.toml:/etc/garage.toml
  #      - .docker/garage/meta:/var/lib/garage/meta
  #      - .docker/garage/data:/var/lib/garage/data

  #  minio:
  #    volumes:
  #      - .docker/minio:/data
  #    image: quay.io/minio/minio:latest
  #    command: server --console-address ":9001" /data/minio
  #    expose:
  #      - '9000'
  #      - '9001'
  #    networks:
  #      - minio
  #    environment:
  #      MINIO_ROOT_USER: admin
  #      MINIO_ROOT_PASSWORD: some-minio-access
  #    healthcheck:
  #      test: ['CMD', 'mc', 'ready', 'local']
  #      interval: 5s
  #      timeout: 5s
  #      retries: 5

  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - '1883:1883'
      - '8883:8883'
      - '9001:9001'
    volumes:
      - .deployment/mosquitto/config:/mosquitto/config
      - .docker/mosquitto/data:/mosquitto/data

networks:
  kafka:
    driver: bridge
