version: '3.8'

services:
  elercam:
    build: .
    container_name: elercam
    restart: unless-stopped
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    networks:
      - mosquitto

networks:
  mosquitto:
    external: true
