name: Build image by tag

on:
  push:
    tags: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Match tag'
        id: regex-match
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ github.ref_name }}
          regex: '^(@?.*)@([\d]+\.[\d]+\.[\d]+.*)'
          flags: g

      - name: 'Exit if tag not matched'
        if: ${{ steps.regex-match.outputs.match == '' }}
        run: |
          echo "Tag was not matched"
          exit 1

      - name: 'Setup env'
        run: |
          echo "APP_NAME=${{ steps.regex-match.outputs.group1 }}" >> $GITHUB_ENV
          echo "APP_CODE=$(echo '${{ steps.regex-match.outputs.group1 }}' | tr '/' '-' | tr -d '@' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "APP_VERSION=${{ steps.regex-match.outputs.group2 }}" >> $GITHUB_ENV
          echo "APP_PATH=$(dirname $(find ./apps -name 'package.json' -exec grep -l '\"name\":\s*"\(${{ steps.regex-match.outputs.group1 }}\)"' {} \;))" >> $GITHUB_ENV

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Extract metadata for the Docker image'
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ghcr.io/${{github.actor}}/${{env.APP_CODE}}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: 'Cat bake-file'
        run: cat ${{ steps.meta.outputs.bake-file }}

      - name: 'Build and push the Docker image'
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: ${{ env.APP_PATH }}/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "APP_RELATIVE_PATH=${{ env.APP_PATH }}"
