name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: read
      statuses: write
      contents: write
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: 'Setup Biome'
      uses: biomejs/setup-biome@v2
      with:
        version: latest

    - name: 'Run Biome'
      run: biome ci .

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: 'Install bun'
      uses: oven-sh/setup-bun@v2

    - name: 'Bulk Release'
      run: DEBUG=1 bunx zx-bulk-release --include-private true --npmFetch false
#      run: bun multi-semantic-release --dry-run --ignore-private=false --ignore-packages="packages/*"
      env:
        GH_USER: test #${{github.actor}}
        GH_TOKEN: foobar #${{secrets.GITHUB_TOKEN}}

    - name: 'Imperative image building'
      run: bunx zx .integration/imperative.mjs --file=.build-meta
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
